### ISSUE TITLE
The constraint about activity's scheduleToClose or scheduleToStart & startToClose should be defined is not enforced

### ISSUE THREAD

**Issue by Spikhalskiy** [temporalio/java-sdk#175] opened 2020-08-12 20:42 UTC
## Expected Behavior

An attempt to configure an Activity with `LocalActivityOptions.newBuilder().build()` should fail, because according to javadoc `scheduleToCloseTimeout` or both `scheduleToStartTimeout` and `startToCloseTimeout` should be defined and there is no default values for these parameters.

## Actual Behavior

We are able to configure an activity stub with `LocalActivityOptions.newBuilder().build()` without any exceptions.

## Specifications

  - Version: current master (https://github.com/temporalio/java-sdk/commit/35abfd425c13e86f16b81e26c85c07b17ee3448f) and 0.28.0

**Comment by mfateev** [comment] 2020-08-21 04:41
This is by design. We moved all activity options validation logic to the service.

**Comment by Spikhalskiy** [comment] 2020-08-21 05:49
@mfateev 
1. Should an implementation for tests also support the validation in that case? Because right now such configuration passes everything in the test environment.
2. Does temporal service enforce the validation of **Local** activity options?

**Comment by mfateev** [comment] 2020-08-24 15:57
Fixed by #194

**Closed by mfateev** 2020-08-24 15:57 UTC
Labels: potential-bug
